### PR TITLE
Show if closed as duplicate... Show if question was reopened... Activity on answers

### PR DESCRIPTION
**Pull request by Istiakshovon**
Resolves : https://physics.codidact.com/posts/283783

Maybe, it's completed : https://meta.codidact.com/posts/279562 I am not sure if anything left for last_activity.

I didn't add locked_at cause, it was looking like when mod lock a post it doesn't bump. Hence, last_activity doesn't change. So, that's not required I think. (Closing doesn't available in answer so, I didn't add it either). If there's anything left then, comment.

Why I didn't fetch children under case?
When I was trying to fetch children under case it was automatically printing those arrays instead of last_activity. Something like returning those arrays instead of 'posted an answer' (or, something just like this).

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
I'm gonna decline this one, for now at least. Showing activity on answers requires us to load all answers to every question we're checking. On the category index page, that means we have to load every question plus all answers, just to show the questions. That doesn't make a huge amount of sense, and isn't going to be great for performance.

**Comment by Istiakshovon** [comment]
So, first two commit helpful? `Show if closed as duplicate... Show if question was reopened`

**Comment by cellio** [comment]
Instead of querying for activity on all answers at page-load time, which I agree would be too expensive, can we store, on a top-level post, the last child activity (if any), and use that when deciding what to show in the post list?  We only need the most recent, not everything from all children.  Doing things to children would have to update this field on the parent, which seems practical?

I don't know how we're storing the time and author of last activity now, though we obviously are, so maybe we could store the "what" at the same time, where "what" is things like answered, answer-edited, answer-deleted, etc?  If we also stored the post ID, we could make the last-activity link be a specific link too, without extra computation at page-load time.

I realize I'm talking around the c-word and cache invalidation is one of the two hard problems in computer science, but since we only ever overwrite this data (don't need to roll it back), maybe that's ok?

**Comment by Istiakshovon** [comment]
@cellio currently, we are storing data of last_activity in DB. And, that shouldn’t be too hard to store last_activity of recent. All the things we have to do that is saving recent_activity in answer (ID of that post). If we save that then we can directly fetch a single answer only. 

But i worry of old post. Old posts didn’t have the field in DB. So i was thinking if it actually affects them. I think command-line may helpful that moment but, i don’t have any idea.

**Comment by ArtOfCode-** [comment]
@Istiakshovon Yep, showing if the question was duped or reopened would be fine.

**Comment by ArtOfCode-** [comment]
@cellio Yep, we could look at doing that. I'm pretty sure we already update last activity on the parent when an answer is changed, so extending that a bit shouldn't be too hard.

**Comment by cellio** [comment]
We must be doing *something*, because you can see "last activity $time $user" when the last activity involves an answer.  That's why I thought it might not be hard to store a little *more* information there -- which answer (to enable linking), what action.  Sounds like I should file a separate issue so it's not tangled in this one?

**Pull request closed without merging**
