### PR TITLE
Markdown parsers

### PR DESCRIPTION
**Pull request by ArtOfCode-**
Switches Markdown parser to using commonmarker on the backend, and markdown-it on the frontend. They should be much closer in terms of configuration, so the preview should be accurate more of the time. We also get superscript, subscript, proper footnotes, proper auto-linkify, and some other things.

This shouldn't cause any visible difference; this PR is here for code review and sanity-check.

### CODE REVIEW

**Comment by cellio** [comment]
How do we do proper superscript/subscript/footnotes?  (Is there documentation we can look at?)

**Comment by ArtOfCode-** [comment]
We should write up some proper Markdown documentation at some point. Superscript and subscript should work via the HTML tags, `sup` and `sub` (and _possibly_ via `^(words)` and `_(words)`, but I wouldn't swear to that). Footnotes are `[^1]` inline, with `[^1]: text` at the bottom, much like URL references.

**Comment by cellio** [comment]
Thanks.  I've been using the HTML tags and realized I have no idea what other notations might be available.

Where would somebody who wants to write up some doc on the markdown we support look for information?  Does the library we're using come with a language spec, for example?

**Comment by ArtOfCode-** [comment]
Generally we should now support CommonMark; there's also good documentation for markdown-it and markdownit-footnote for specifics.

This is also up on dev for poking at now.

**Comment by cellio** [comment]
Superscript and subscript on https://dev.codidact.org/a/3092/3097 looked fine in the preview but don't render right in the final post.

**Comment by ArtOfCode-** [comment]
Should be fixed now.

**Comment by cellio** [comment]
Confirmed; that looks right now.

**Pull request merged**
