### PR TITLE
attempt a fix for issue #136

### PR DESCRIPTION
**Pull request by galegosimpatico**
Tests are missing, I know. Would add upon request.

Some lines are too large.

I'll try fixing all of that if the PR is reviewed "reasonable" overall.

I mean IDK if wontfix is reasonable at this point. :shrug:

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
I suspect there's a much easier way to do this, rather than messing with Unicode (again...): just stick an LTR-override character before and after every username, regardless of whether it's actually got RTL in it or not.

Could be done by implementing a `ltr_safe_username` method on User which simply returns `"\u202D#{username}\u202D"`, then searching for all `username` calls in views and replacing them with `ltr_safe_username`.

**Comment by galegosimpatico** [comment]
> I suspect there's a much easier way to do this, rather than messing with Unicode (again...): just stick an LTR-override character before and after every username, regardless of whether it's actually got RTL in it or not.
> 
> Could be done by implementing a `ltr_safe_username` method on User which simply returns `"\u202D#{username}\u202D"`, then searching for all `username` calls in views and replacing them with `ltr_safe_username`.

I hadn't tried that exactly... before arriving to this contrived idea, I tried to set up LTR override jails like that, just done in HTML because I suck so much at Ruby, but that didn't fix my stuff. Now I just tried your idea and didn't fix it either.

At least now I picture how to create a chain of directional formatting pops within a Ruby sanitizing function without resorting to a template loop on adding the HTML escape sequence of the directional formatting pop over and over again.

😕

**Comment by ArtOfCode-** [comment]
Okay, got it. Add this method to User:

```ruby
def rtl_safe_username
  "\u202D#{username}\u202D"
end
```

Then, for any usage of `u.username` in a view, where `u` is a User instance, replace it with `u.rtl_safe_username`, _and_ add a `dir="ltr"` attribute to the surrounding HTML element (add a `<span>` for containment if necessary).

**Comment by galegosimpatico** [comment]
If you are sure, then I should yield it so you can have parent issue becoming [meta: good first issue][0].

[0]: https://github.com/codidact/qpixel/labels/meta%3A%20good%20first%20issue

**Comment by ArtOfCode-** [comment]
I don't mind at all - if you want it, you're welcome to it; no point letting stuff sit around for ages just because a new contributor _might_ want to do it.

**Comment by galegosimpatico** [comment]
I couldn't care less about what's cooking in no tag's land.

**Pull request closed without merging**
