### PR TITLE
Add missing title/score block for article history

### PR DESCRIPTION
**Pull request by rileyradoll**
Closes: #206

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
Thanks for your work on this! There's an easier way to solve this one, though: the `posts/_type_agnostic` view is a "list" view that works regardless of post type. Instead of creating a new article-list view, can we instead use the type agnostic view and just remove any "if post type is question/answer" conditionals?

**Comment by cellio** [comment]
A question list can have a mix of questions and articles; it's not necessarily just one type.  (See Judaism's Challenges for an example.)  I didn't expect lists to be involved here and maybe I'm misunderstanding Art's comment, but mentioning this just in case it's relevant.

**Comment by ArtOfCode-** [comment]
"list" is just the name of the view used here, @cellio - it's not part of a list, just using the same format

**Comment by rileyradoll** [comment]
@ArtOfCode- @cellio thanks for the feedback and context. I'll get this changed this weekend.

**Comment by cellio** [comment]
Hi, just checking in.  Were you able to make those changes?  Thanks.

**Comment by rileyradoll** [comment]
Still working on this. Will have something soon.

**Comment by rileyradoll** [comment]
@ArtOfCode- Made some changes based on your feedback. Let me know if you'd like to see more changes. Thanks!

**Comment by ArtOfCode-** [comment]
Thanks!

**Pull request merged**
