### PR TITLE
Update _new_thread_modal.html.erb

### PR DESCRIPTION
**Pull request by Istiakshovon**
Screenshot from 2021-07-13 12-14-20

Since, I couldn't edit multiple files in https://github.com/codidact/qpixel/pull/552 . That's why I am creating it. And, also sorry for I can't add multiple files here. I literally don't know how to PR multiple files in a commit. 

https://github.com/codidact/qpixel/pull/559

### CODE REVIEW

**Comment by FoggyFinder** [comment]
> Since, I couldn't edit multiple files in #552 . That's why I am creating it. And, also sorry for I can't add multiple files here. I literally don't know how to PR multiple files in a commit.

So currently you're using web interface to create PR, right?

**Comment by Istiakshovon** [comment]
@FoggyFinder yes

**Comment by FoggyFinder** [comment]
Well, it does look like a good Q for [Power User](https://powerusers.codidact.com) community

Anyway, I suggest you avoiding web-interface for something that is more complicated that an one-line fix. There're plenty of good tools that help you to get started with git & github quickly.

I personally use [Git Extensions](http://gitextensions.github.io) which is awesome so you don't have to know / learn git commands yet. It works smoothly for all simple cases.

See [docs](https://git-extensions-documentation.readthedocs.io/en/release-3.4/) for details.

In short, the flow would look like that:

1. Create a fork of a repository (you've done it already - [Istiakshovon/qpixel](https://github.com/Istiakshovon/qpixel)).
2. Clone it locally.
3. Create a branch for a specific fix or improvements (you've done it already and its name is `patch-11`).
4. Make changes to whatever you feel to change there.
5. Index these changes.
6. Make a commit.
7. Push a commit to the repo.
8. Create/Update PR to the upstream repo (a this one).
9. Iff the work isn't finished then return to 4 and repeat

Actually it will be easier that it sounds. 

Anyway, if you go with GitExtensions I can describe steps above more thoroughly. Feel free to ask if something isn't clear.

**Comment by Istiakshovon** [comment]
Some bug is available. So, I am just closing it.

**Pull request closed without merging**
