### PR TITLE
Add counter for undeleted posts on CommunityUser

### PR DESCRIPTION
**Pull request by ArtOfCode-**
See #1411.

Adds an automatic counter for undeleted posts on CommunityUser.

> **Deploy note**  
> When this is deployed a manual process will be needed to set initial values for these counters.

### CODE REVIEW

**Review by Oaphi — CHANGES_REQUESTED** [review]
I presume we also no longer need the `post_count` method on the [`community_user` model](https://github.com/codidact/qpixel/blob/64aeaa700b90b2955b9d7f02d287937f8a538706/app/models/community_user.rb#L28-L30) then (apologies for a no-preview link, [review comments on unchanged files](https://github.com/orgs/community/discussions/9099) are still not supported)?

**Comment by ArtOfCode-** [comment]
> I presume we also no longer need the `post_count` method on the [`community_user` model](https://github.com/codidact/qpixel/blob/64aeaa700b90b2955b9d7f02d287937f8a538706/app/models/community_user.rb#L28-L30) then?

You would be correct, removed :)

**Comment by Oaphi** [comment]
LGTM!

**Review by Oaphi — APPROVED** [review]

**Comment by cellio** [comment]
> > **Deploy note**
> > When this is deployed a manual process will be needed to set initial values for these counters.

What happens if this gets deployed and that doesn't happen?  Does it just not get cached (yet), or does something break?  (This is a question about timing: does somebody need to be able to jump on this at the time of the next deploy?)

**Pull request merged**
