### PR TITLE
Add doc to storage.sample.yml

### PR DESCRIPTION
**Pull request by cellio**
Per https://github.com/codidact/qpixel/pull/1041#issuecomment-1545849997 -- added some comments explaining how to use this in a non-S3 environment.

I tested these instructions in my dev environment.

### CODE REVIEW

**Comment by cellio** [comment]
I guess I need to rebase this on `develop` but I'm not quite sure how to do that without making a mess.  The first commit her was already merged; didn't realize my local environment wasn't proper.

**Comment by trichoplax** [comment]
The documenting comment looks good to me.

**Comment by trichoplax** [comment]
As for the rebasing, the [git rebase documentation](https://git-scm.com/docs/git-rebase) suggests that the redundant commit (that is present in both `develop` and your new branch) should automatically be discarded if you rebase, so you shouldn't need a complicated command that tells git which commits to keep.

You should be able to just do the following:

```text
git pull
git checkout "cellio/storage-yaml-doc"
git rebase develop
```

You can then use `git log` to check that you have the commits you expect before you push. After that, this pull request should only have the documentation commit, and not the other commit that is already in develop.

Worst case, you end up with an extra commit and we'll resort to the longer form of `git rebase`, but it sounds like that won't be necessary.

**Comment by cellio** [comment]
I rebased and now there are _more_ diffs (that I did not make).  Y'know what?  This is a trivial change; I'm not going to try to fix this branch when I can just reimplement it.

**Comment by cellio** [comment]
New clean PR: https://github.com/codidact/qpixel/pull/1050 .

**Pull request closed without merging**
