### PR TITLE
Rewording to specify that editing follows the goals of the post, not the poster

### PR DESCRIPTION
**Pull request by ws909**
Clarify that it's the goal of the post itself which matters, and not that of its author. The author's goals may change, or they may have created a post which turned out not to be aligned with the goals they had. Once a post has been committed to Codidact, the author's goals cease, and the network's goals with the post take effect.

### CODE REVIEW

**Comment by ws909** [comment]
Oh, it's been a while since I edited directly on Github, so I managed to mess up the commit titles. Should I fix that, or will they be squashed at merge?

**Comment by trichoplax** [comment]
Is there any existing documentation that supports this assertion? If not, we could have a Meta discussion to see if there is support for changing from the current stance that an author owns their own posts.

**Comment by ws909** [comment]
As far as I’m concerned, that posts are owned by the network, and not the author, is one of the pillars of Codidact, and any quality curated Q/A.

Other than this very document, I have never seen any established stance that authors are fully in control of their posts, and that would also run counter to the goals of the network, the way I understand it. 

Certainly, you’d grant original authors a greater level of autonomy in deciding the fate of their posts in the meta category, but that would be the exception, and not the rule.

**Comment by ArtOfCode-** [comment]
Suggestion: instead of "respect the goal of the post" (which reads odd - a person can have goals, but a post?), consider "preserve the intention of the post".

**Comment by ws909** [comment]
That's much better wording, indeed.

**Review by ArtOfCode- — APPROVED** [review]

**Pull request merged**
