### PR TITLE
Highlight answers from deleted questions as such.

### PR DESCRIPTION
**Pull request by galegosimpatico**
Applies https://github.com/codidact/qpixel/issues/153#issuecomment-684014452.

---

Checklist for https://github.com/codidact/qpixel/pull/177#pullrequestreview-489434537:

* [x] `app/models/question.rb:    Answer.where(parent: self)` (answers of a question, so the parent is already there).
* [x] `app/controllers/tags_controller.rb:    @posts = Post.where(id: post_ids).undeleted.where(post_type_id: @category.display_post_types)` (only articles and questions - ids come from `post_ids_for_tags`, which selects from `post_tags`, which don't store for answers - see `SELECT name FROM post_types WHERE id IN (SELECT post_type_id FROM posts WHERE id IN (SELECT post_id FROM posts_tags));`).
* [x] `app/controllers/questions_controller.rb:                 Answer.where(parent_id: @question.id)` (the parent question record is already retrieved - it's the data used for `where` filtering).
* [x] `app/controllers/questions_controller.rb:                 Answer.where(parent_id: @question.id).undeleted` (the parent question record is already retrieved - it's the data used for `where` filtering).
* [x] `app/controllers/questions_controller.rb:                       .or(Answer.where(parent_id: @question.id, user_id: current_user&.id))` (the parent question record is already retrieved - it's the data used for `where` filtering).
* [ ] `app/controllers/users_controller.rb:    @post_counts = Post.where(user_id: @users.pluck(:id).uniq).group(:user_id).count`.
* [ ] `app/controllers/users_controller.rb:    @posts = Post.where(user: @user).count`.
* [ ] `app/controllers/users_controller.rb:    @interesting_posts = Post.where(user: @user).where('score < 0.25 OR deleted=1').count`.
* [ ] `app/controllers/users_controller.rb:                Post.where(user: @user).all`.
* [ ] `app/controllers/users_controller.rb:                  Post.where(user: @user).where('score < 0.25 OR deleted=1').all`.
* [ ] `app/controllers/users_controller.rb:                Post.where(user: @user).all + Comment.where(user: @user).all + Flag.where(user: @user).all + \`.
* [x] `app/controllers/reports_controller.rb:    @questions = Question.where('created_at >= ?', 1.year.ago).undeleted` (question).
* [ ] `app/controllers/reports_controller.rb:    @answers = Answer.where('created_at >= ?', 1.year.ago).undeleted`.
* [ ] `app/controllers/reports_controller.rb:    @this_month = Post.where('created_at >= ?', 1.month.ago).undeleted`.
* [ ] `app/controllers/posts_controller.rb:    @posts = Post.where(post_type_id: [PolicyDoc.post_type_id, HelpDoc.post_type_id])`.

### CODE REVIEW

**Review by luap42 — APPROVED** [review]
Looks good, although I’d rename the helper method. I don’t think the name describes what it does well currently.

**Comment by galegosimpatico** [comment]
`deleted_or_parent_deleted`

**Comment by cellio** [comment]
Does this change the *rendering* (showing answers to deleted questions as deleted), or does it change their *state* to "deleted"?  After the data import on Judaism we had a bunch of deleted questions (duplicate imports) where the answers weren't deleted, and those links showed on people's profiles.  Then if you tried to follow the link you got an error because the question page was deleted.  That suggests to me that they were not marked as deleted in the database, so not only a rendering problem.  (I've since cleaned those up, so you'll need to get another test case.)

**Comment by luap42** [comment]
@cellio this changes the rendering. Basically, there’s a new check, that returns yes for an answer, when either it or its parent is deleted. 

@galegosimpatico the new name is fine. Although, cellio's comment raises an important point. You need to look, whether the old function is used somewhere else. There are cases in the answer controller and the post list AFAICT, not sure if others too.

**Comment by galegosimpatico** [comment]
It seems the user profile reuses the same posts list, because these changes highlight them there too (but I didn't know). Big cheer for good architecture!

**Review by ArtOfCode- — CHANGES_REQUESTED** [review]
No issues with the code here, but we need to make sure that anywhere it's being _used_, we need to be preloading parents as well as just answers, otherwise we hit an N+1 problem and end up querying for answers and then once for every parent, instead of answers plus parents.

Places where this is a problem will probably look something like `Answer.where(...)` or `Post.where(post_type_id: Answer.post_type_id, ...)` with _no_ `includes` call, or with an `includes` call that doesn't include `:parent`. Fixing them should be as simple as adding `.includes(:parent)` to the ActiveRecord query, or adding `:parent` to the arguments if there is one already.

**Comment by galegosimpatico** [comment]
<details>
<summary>postit</summary>

```
$ grep -ri 'Post.where\|Answer.where\|Question.where\|Article.where' app | sed s/:.*// | sort -u | nl
     1	app/controllers/posts_controller.rb
     2	app/controllers/questions_controller.rb
     3	app/controllers/reports_controller.rb
     4	app/controllers/tags_controller.rb
     5	app/controllers/users_controller.rb
     6	app/models/question.rb
$ grep -ri 'Post.where\|Answer.where\|Question.where\|Article.where' app | nl
     1	app/models/question.rb:    Answer.where(parent: self)
     2	app/controllers/tags_controller.rb:    @posts = Post.where(id: post_ids).undeleted.where(post_type_id: @category.display_post_types)
     3	app/controllers/questions_controller.rb:                 Answer.where(parent_id: @question.id)
     4	app/controllers/questions_controller.rb:                 Answer.where(parent_id: @question.id).undeleted
     5	app/controllers/questions_controller.rb:                       .or(Answer.where(parent_id: @question.id, user_id: current_user&.id))
     6	app/controllers/users_controller.rb:    @post_counts = Post.where(user_id: @users.pluck(:id).uniq).group(:user_id).count
     7	app/controllers/users_controller.rb:    @posts = Post.where(user: @user).count
     8	app/controllers/users_controller.rb:    @interesting_posts = Post.where(user: @user).where('score < 0.25 OR deleted=1').count
     9	app/controllers/users_controller.rb:                Post.where(user: @user).all
    10	app/controllers/users_controller.rb:                  Post.where(user: @user).where('score < 0.25 OR deleted=1').all
    11	app/controllers/users_controller.rb:                Post.where(user: @user).all + Comment.where(user: @user).all + Flag.where(user: @user).all + \
    12	app/controllers/reports_controller.rb:    @questions = Question.where('created_at >= ?', 1.year.ago).undeleted
    13	app/controllers/reports_controller.rb:    @answers = Answer.where('created_at >= ?', 1.year.ago).undeleted
    14	app/controllers/reports_controller.rb:    @this_month = Post.where('created_at >= ?', 1.month.ago).undeleted
    15	app/controllers/posts_controller.rb:    @posts = Post.where(post_type_id: [PolicyDoc.post_type_id, HelpDoc.post_type_id])
$ _
```

</details>

**Pull request closed without merging**
