### PR TITLE
Filters updated

### PR DESCRIPTION
**Pull request by Taeir**
### All credit for this feature goes to @MoshiKoi 
I have only addressed some of the PR comments and fixed some minor issues as indicated in the original PR #890.

Since I am not able to add changes directly to someone else's branch/fork of the repo, I had to create a new branch and PR.

### CODE REVIEW

**Comment by Taeir** [comment]
@ArtOfCode- With the changes in this PR, `search_helper` becomes longer than the currently set maximum of 200 lines for a Module. I feel like splitting it up into multiple modules is not really going to improve anything. How should I address this? I can:

* Exclude this particular file
* Increase the max module length limit

Or perhaps you have other suggestions?

**Comment by ArtOfCode-** [comment]
@Taeir I'd increase the limit. 200 is probably a number mostly out of thin air - in this case it's not enough, so let's make it more.

**Review by ArtOfCode- — APPROVED** [review]
LGTM, approving, not merging right now because of deploy sequencing.

**Comment by cellio** [comment]
@ArtOfCode- is the "deploy sequencing" concern still an issue?

**Pull request merged**
