### PR TITLE
Accessibility and Bugfix updates

### PR DESCRIPTION
**Pull request by luap42**
This closes a few Co-Design issues by updating to 0.4.2 and a few accessibility issues noted by @cellio, where the most notable is the increase of the post body font size from 16px to 18px.

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
I'm gonna veto the 18px post body font. I get where it's coming from, but (IMO, at least) it's just _too_ big. 16px is about right for reading. We should, of course, make sure the site doesn't break on higher zoom levels or if folks userstyle in larger text.

**Comment by ArtOfCode-** [comment]
Couple other comments, but they seem to be Co-Design things so I'll drop issues over there.

**Comment by cellio** [comment]
> 
> 
> I'm gonna veto the 18px post body font. I get where it's coming from, but (IMO, at least) it's just _too_ big. 16px is about right for reading. We should, of course, make sure the site doesn't break on higher zoom levels or if folks userstyle in larger text.

Someone who thinks it's too big can zoom down a notch, but for those for whom it's too small, zooming up breaks the responsive design.  Our fonts are out of *proportion* with each other; headers are too huge for a 16px body, so there is no zoom setting that doesn't make one or the other look bad.

I should not have to use client-side CSS to override a design that breaks something that used to work on a platform I'm supposed to be helping to build. :-(  I'm not asking for something unreasonable like 20+px.  Either scale other things to fit the smaller body size *and make the responsive design work with zoom*, or make this change please.  It's important.

**Comment by ArtOfCode-** [comment]
Closing this one for ease - I'll update the package and make some other changes on master.

**Comment by cellio** [comment]
I object.

**Comment by ArtOfCode-** [comment]
@cellio Still working on this, just not in this particular PR is all - it's easier to make the changes on master at this point. Updates deployed.

**Pull request closed without merging**
