### PR TITLE
generalized footer

### PR DESCRIPTION
**Pull request by cellio**
Sorted the footer links into "this network" and "Codidact project".  Replaced the generated list of communities (which was getting long and was a little buggy) with a dashboard link.  Added some wayfinding to the dashboard page, including pointer to the communities switcher.

This change removes the baked-in `codidact.com` link that is incorrect for other networks.  I added the GitHub link under "Codidact project" to make the OSS platform a little more visible on other networks (maybe they want to contribute too).

Closes https://github.com/codidact/qpixel/issues/1349 and (indirectly) https://github.com/codidact/qpixel/issues/1216.

### CODE REVIEW

**Review by Oaphi — APPROVED** [review]
LGTM. The only change I'd make, though, is changing "This Network" to something else. If it confuses _me_, pretty sure it will be even more confusing to outside users. Non-blocking, though (and I honestly have no idea how to word it better).

**Comment by cellio** [comment]
> LGTM. The only change I'd make, though, is changing "This Network" to something else. If it confuses _me_, pretty sure it will be even more confusing to outside users. Non-blocking, though (and I honestly have no idea how to word it better).

I'm certainly open to changing it -- I'm just not sure to what. "Communities on this server" doesn't seem much clearer, and I don't think "instance" is widely understood.

**Comment by trichoplax** [comment]
> > LGTM. The only change I'd make, though, is changing "This Network" to something else. If it confuses _me_, pretty sure it will be even more confusing to outside users. Non-blocking, though (and I honestly have no idea how to word it better).
> 
> I'm certainly open to changing it -- I'm just not sure to what. "Communities on this server" doesn't seem much clearer, and I don't think "instance" is widely understood.

Short answer:  
Go with "the network" or (my preference) leave it out altogether.

Long answer:  
Websites are understood to be self contained. A supermarket website listing "All products" doesn't need to mention "(by the way, this is only all products for our company - products from other companies are not listed here)". Users of any particular instance of QPixel don't need to know what an instance is, or that there are other networks, any more than they need to know what programming language we use.

In the paragraph on the dashboard, I would probably say something like:

> All communities, with their categories. You can also see the communities from the dropdown arrow at the top right of each page.

(Less to read and less to be confused about.)

In the footer, I would expect the separation into two sections to have no meaning for many users, and to be a source of confusion. Unless I already know about Codidact, the heading "The Codidact Project" is unlikely to change my expectation that the link "contact us" will be to contact the owners of the website. For every instance except one, this will be incorrect.

My suggestion would be to remove the two section headings, and only include links that relate to the instance (ideally in a way that is configurable without needing a code change). "About us" and "Contact us" should both relate to the instance. Perhaps in future work they could become relative URLs like the others.

There can then be a single link to codidact.org with text that distinguishes it from all the other links, which are instance-specific. Perhaps something like "Powered by Codidact" (please someone suggest something better). This could possibly be separate from the bullet point list of links (I can imagine it in the version label below the footer:

> Powered by [Codidact](https://codidact.org/). Version [604d40c6](https://github.com/codidact/qpixel/commit/604d40c6c03ce445032f58cec1f67e4c445d0351) (2024-09-11 04:12:24 +0100)

If I want to read about or contact Codidact, I can follow that link and understand that any links on that new page relate to Codidact, which powers the website I just left. I think this will be clearer to users than trying to have both a "Contact Codidact" and "Contact Acme" (for the instance) in the same footer.

Parts of this that sound reasonable might be best in other issues - I'm not suggesting we do everything in one pull request.

**Comment by cellio** [comment]
@trichoplax I've made some adjustments, thanks, including moving support/contact info into the network FAQ where other instances can edit it.  On-site config would be even better...someday.

**Comment by Oaphi** [comment]
Minor nit for the network FAQ: specifying "software" twice in a row is unnecessary, and a more appropriate term would be "engine", imo:

> This community is built with the [open-source QPixel engine](https://github.com/codidact/qpixel) provided by [The Codidact Foundation](https://codidact.org/). The software is free, open-source, and highly customizable.

**Comment by Oaphi** [comment]
@cellio to follow up on my note about the timestamp format, here is a quick fixup: https://github.com/codidact/qpixel/pull/1402

**Pull request merged**
