### PR TITLE
updating hover text of upvote and downvote

### PR DESCRIPTION
**Pull request by Istiakshovon**
Earlier it was only showing score point which was very confusing. And, new user would know by seeing the hover text what it does.

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
Thanks! Can we make these just say `"Score: <%= post.score %>"` instead? I don't think it needs any further explanation in the tooltip. (New lines also don't have great cross-browser support.)

**Comment by cellio** [comment]
> Thanks! Can we make these just say `"Score: <%= post.score %>"` instead? I don't think it needs any further explanation in the tooltip. (New lines also don't have great cross-browser support.)

Can we add "(0-1)" or "(scale: 0-1)" after the score? The fractional values might confuse folks expecting "up minus down".

**Comment by Istiakshovon** [comment]
> Thanks! Can we make these just say `"Score: <%= post.score %>"` instead? I don't think it needs any further explanation in the tooltip. (New lines also don't have great cross-browser support.)

`New lines also don't have great cross-browser support.` I didn't have the idea. That's why I wrote it. Cause, sometimes new user get issue to understand what does it do. When I was completely new to SO I was checking all of them cause, I didn't know what they do. Even, I forgot to read hover text. Than, `"Score: <%= post.score %>"` is ok.! :)

**Comment by Istiakshovon** [comment]
> > Thanks! Can we make these just say `"Score: <%= post.score %>"` instead? I don't think it needs any further explanation in the tooltip. (New lines also don't have great cross-browser support.)
> 
> Can we add "(0-1)" or "(scale: 0-1)" after the score? The fractional values might confuse folks expecting "up minus down".

I think no! Cause, 'upvote' and 'downvote' score shows between those buttons. So, I don't think it is necessary.

**Comment by cellio** [comment]
Oh right, the vote breakdown is right there -- so people should be able to interpret the number with the additional hint that it's a score.

**Pull request merged**
