### PR TITLE
Show character length while editing comments

### PR DESCRIPTION
**Pull request by Istiakshovon**
https://meta.codidact.com/posts/282342/282410#answer-282410
https://github.com/codidact/qpixel/issues/204

 I haven't test the code. 
 
 tested... not working... I will check it

### CODE REVIEW

**Comment by Istiakshovon** [comment]
It's working now.. But, I can see some problem right there....

@ArtOfCode- you told me to use `hide` class instead of style="display:'none' ". I noticed that the hide class isn't removing whenever character touches 75% of that.

**Comment by ArtOfCode-** [comment]
Inline `style` attributes aren't a good thing to use in most cases, because they override basically everything which makes it very difficult to change styles anywhere else you want to do so. This is happening because I wrote the code to hide the character counter without taking into account how our `hide` class works, so instead of adding and removing that class I've used jQuery's specific `hide()` and `show()` methods, which work differently. I'm going to merge this as-is for now and hopefully get round to fixing that so we can remove the inline `style` at some later date.

**Comment by cellio** [comment]
I just tried to edit a comment and I don't see a counter.

**Comment by Istiakshovon** [comment]
> I just tried to edit a comment and I don't see a counter.

It will show when you approach limit 
Screenshot from 2021-08-16 15-12-10

**Comment by cellio** [comment]
Ah.  I was confused because for a *new* comment the counter is always there.

**Comment by Istiakshovon** [comment]
> Ah. I was confused because for a _new_ comment the counter is always there.

So, should we show that counter always?

**Comment by cellio** [comment]
I think it would be better if we matched with comment creation, thanks.

**Pull request merged**
