### PR TITLE
User profile: votes by date

### PR DESCRIPTION
**Pull request by galegosimpatico**
Playfully approach https://github.com/codidact/qpixel/issues/133.

### CODE REVIEW

**Comment by cellio** [comment]
Could you add a screen shot, for those of us who can't just mentally compile and execute the code? :-)  Thanks.

**Comment by galegosimpatico** [comment]
Screenshot 2020-10-26 at 15 33 34

**Comment by galegosimpatico** [comment]
um missed some kind of header, which wasn't necessary for casted votes because it was fitting in the same section

**Comment by galegosimpatico** [comment]
Screenshot 2020-10-26 at 15 39 44

**Comment by galegosimpatico** [comment]
* [ ] Check freshly created user.

**Comment by cellio** [comment]
Thanks for adding the header; was typing a comment about that when you fixed it. :-)

What happens when there are hundreds of votes?  Pagination?  (Ultimately we probably want a separate tab on the user profile for this, but if a long list doesn't overwhelm the page, we can do that later.)

**Comment by galegosimpatico** [comment]
> What happens when there are hundreds of votes? Pagination? [...]

ATTOW only the most recent few comments are printed.

* [ ] "Received votes" auto transforming to "Recently received votes" when there are more 'received votes' than `how_many`.

**Comment by galegosimpatico** [comment]
The new layout breaks visualization of this; let's get back here at some point later - won't remove the branch or commits.

**Pull request closed without merging**
