### PR TITLE
tackling comment character count not updating when pasting and cutting from context menu

### PR DESCRIPTION
**Pull request by galegosimpatico**
tries to bind character count to mouse events too

tackles [Comment character count doesn't update for insert from
context menu](https://github.com/codidact/qpixel/issues/211)

works for me

early wip

will reformat

cheers

### CODE REVIEW

**Comment by MoshiKoi** [comment]
I believe you can just do `$target.on('keyup cut paste cutcc-reset', ` all in one instead of repeatedly using .bind

I also suggest binding 'input' which by specification will catch any and every change, the rest is basically support for browsers that don't fully support 'input' (which tbh shouldn't be many).

https://stackoverflow.com/questions/5494648/catching-all-changes-to-the-contents-of-an-input-box-using-javascript-jquery/5494697#5494697

**Comment by ArtOfCode-** [comment]
:+1: as Moshi says for merging all the triggers into one `on` call. Also worth noting that `bind` is not the preferred method of doing it - better to use `on`.

**Review by ArtOfCode- — CHANGES_REQUESTED** [review]
:+1: as Moshi says for merging all the triggers into one on call. Also worth noting that `bind` is not the preferred method of doing it - better to use `on`.

**Comment by galegosimpatico** [comment]
aye

**Comment by galegosimpatico** [comment]
but well the timing sh is necessary (just remembered), so the only thing we can do here is to merge paste and cut - which will do.

OR

apply the timeout to everything. Which is more condensed but would use the timing sh even when it's not necessary

thx 4 ur input!

**Comment by ArtOfCode-** [comment]
Okay, if the timing's necessary let's do as you suggest and just merge paste and cut - we should also change the `bind` to `on`, then we're good to go.

**Comment by galegosimpatico** [comment]
I have checked (hence [here][0] and [here][1]) how to use `on` instead of `bind` unfortunately doesn't remove the need for the timed wait. :(

[0]: https://github.com/codidact/qpixel/pull/219#event-3916805324
[1]: https://github.com/codidact/qpixel/pull/219#event-3916807110

**Comment by galegosimpatico** [comment]
> [...]
> 
> I also suggest binding 'input' which by specification will catch any and every change, the rest is basically support for browsers that don't fully support 'input' (which tbh shouldn't be many).
> 
> [...]

I'm not investigating this myself, but only because I've read, elsewhere, the comments system will be completely revamped.

**Pull request merged**
