### PR TITLE
collapse filter on search results page

### PR DESCRIPTION
**Pull request by cellio**
https://meta.codidact.com/posts/288181

On search results, collapse the filter widget by default and also move it to right above the list of posts (for consistency).  This puts the guidance about search grammar right next to the textbox where you can type it, and puts the filters right next to the posts like on the category page.

Thanks to @MoshiKoi for helping me find the right place to update.

This is what that page looks like now:

screenshot

### CODE REVIEW

**Comment by MoshiKoi** [comment]
it appears to break the filters.

image

Selecting a filter doesn't fill in anything, and none of the buttons work when clicked on either

**Comment by cellio** [comment]
Uh oh.  That's not good.

**Comment by cellio** [comment]
I can't reproduce what MoshiKoi is seeing (help, please!), and I'm also mystified by how relocating some static text and an invocation like this would break it.  I'd like to learn from this; I'm stuck.

**Comment by MoshiKoi** [comment]
Woops, misclicked (was going to comment that the most recent commit fixed the issue I mentioned)

**Review by MoshiKoi — APPROVED** [review]

**Pull request merged**
